---
- hosts: 172.31.28.200
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present

  - name: i want to copy static files into ansible nodes side
    tamplete: 
       src: mystaticfile.html
       dest: /var//www/html/index.html

