---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2
    apt:
      name: "{{mywebpakonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
    
  - name: i want to start apache2
    service:
      name: "{{mywebpakonubuntu}}"
      state: restarted
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on redhat nodes
    yum:
     name: "{{mywebpackonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"  

  - name: i want to start a webserver
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family =="RedHat" 

